name: Daily Forecast Update

on:
  schedule:
    - cron: '00 12 * * *'  # 08:00 Bolivia time (UTC-4)
  workflow_dispatch:

jobs:
  update-forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Write CDS API credentials
        run: |
          ls
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r early-warning-system/requirements.txt

      - name: Write CDS API credentials
        run: |
          echo "url: ${{ secrets.CDSAPI_URL }}" > ~/.cdsapirc
          echo "key: ${{ secrets.CDSAPI_KEY }}" >> ~/.cdsapirc

      - name: Run forecast update
        run: |
          python early-warning-system/notebooks/update_forecast.py

      - name: Commit updated data files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: daily forecast update $(date +'%Y-%m-%d')"
          commit_user_name: Gabriel [GitHub Actions]
          commit_user_email: 98acga98@gmail.com
          file_pattern: early-warning-system/data/**
